version: '3.8'

services:
  db:
    container_name: homster-db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin-user
      POSTGRES_PASSWORD: admin-password
      POSTGRES_DB: homster-db
      PGDATA: /data/postgres
    volumes:
       - db-volume:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app-network
    restart: unless-stopped
  queues:
    container_name: homster-queues
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-volume:/data/redis
    networks:
      - app-network
    restart: unless-stopped
    
networks:
  app-network:
    driver: bridge

volumes:
  db-volume:
  redis-volume: